import Head from 'next/head'
import Link from 'next/link'
import Home from '../components/Home';
import Login from '../components/Login';
import CreateAccount from '../components/CreateAccount';
import Navbar from '../components/Navbar'
import ContentView from '../components/ContentView';

function App() {
  	return (
	<div>
      	<Head>
        	<title>Math Generator</title>
    		<meta name="description" content="Generated by create next app" />
        	<meta name="viewport" content="width=device-width, initial-scale=1" />
      	</Head>
      	<Navbar />
      	<ContentView />
    </div>
  	);
}

export default App;
